<?php
/**
 * @var \Faiz\MaintenanceMode\Block\MaintenancePage $block
 */
?>
<style>
        .page-wrapper {
            background-image: url("<?php echo $block->getBackgroundImageUrl() ?>");
            background-size: cover;
            background-repeat: no-repeat;
            background-position: center;
            background-color : <?php echo $block->getBackgroundColor(); ?>;
        }
        .page-main {
            display: flex;
            justify-content: center;
            flex-direction: column;
        }
        .content-wrapper {
            padding: 10rem;
            text-align: center;
            font-size: 5rem;
            display : flex;
        }
        .timer-block {
            display: block;
            min-width : 30vw;
            margin :auto;
        }
        .timer-block > div {
            display: inline-block;
            text-align: center;
            background: #0a0a0a20;
            box-shadow: #0000002f .5rem .6rem .5rem;
            border-radius: 2rem;
            min-width : 10rem;
            min-height : 12rem;
        }
        .timer-block .smalltext {
            font-size: 2rem;
        }
    </style>

    <div class="content-wrapper">
        <div class="html-text-content">
            <?php echo $block->getHtmlContent(); ?>
        </div>
        <?php if($block->isCountEnabled()) { ?>
        <div id="countdown" class="timer-block">
            <div>
                <span class="days"></span>
                <div class="smalltext">Days</div>
            </div>
            <div>
                <span class="hours"></span>
                <div class="smalltext">Hours</div>
            </div>
            <div>
                <span class="minutes"></span>
                <div class="smalltext">Minutes</div>
            </div>
            <div>
                <span class="seconds"></span>
                <div class="smalltext">Seconds</div>
            </div>
        </div>
            <script>
                require(['jquery'], function ($) {
                    $(document).ready(function () {
                        const targetTimestamp = <?php echo $block->getEndTimeStamp() - $block->getTimeOffset();?> * 1000 ;

                        function updateCountdown() {
                            var now = new Date().getTime();
                            var timeLeft = targetTimestamp - now;

                            if (timeLeft <= 0) {
                                clearInterval(intervalId);
                                timeLeft = 0;
                            }

                            var days = Math.floor(timeLeft / (1000 * 60 * 60 * 24));
                            var hours = Math.floor((timeLeft % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
                            var minutes = Math.floor((timeLeft % (1000 * 60 * 60)) / (1000 * 60));
                            var seconds = Math.floor((timeLeft % (1000 * 60)) / 1000);

                            $('#countdown .days').text(days);
                            $('#countdown .hours').text(hours);
                            $('#countdown .minutes').text(minutes);
                            $('#countdown .seconds').text(seconds);
                        }

                        var intervalId = setInterval(updateCountdown, 1000);
                        updateCountdown();
                    });
                });
            </script>
        <?php } ?>
    </div>
